name: dayly tests at 16:00

on:
  schedule:
    - cron: '0 16 * * *'

env:
  SPOND_API_URL: ${{ secrets.SPOND_API_URL }}
  SPOND_USERNAME: ${{ secrets.SPOND_USERNAME }}
  SPOND_PASSWORD: ${{ secrets.SPOND_PASSWORD }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: install dependancies
        run: npm ci

      - name: run tests
        run: npm test

      - name: notify in discord
        if: ${{ failure() }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"content":"Tests failed"}' ${{ secrets.DISCORD_WEBHOOK_URL }}
