name: main workflow

on:
  push:
    branches:
      - master
env:
  SPOND_API_URL: ${{ secrets.SPOND_API_URL }}
  SPOND_USERNAME: ${{ secrets.SPOND_USERNAME }}
  SPOND_PASSWORD: ${{ secrets.SPOND_PASSWORD }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: install dependancies
        run: npm ci

      - name: run tests
        run: npm test
