name: Node.js Package

on:
  release:
    types: [created]

env:
  SPOND_API_URL: ${{ secrets.SPOND_API_URL }}
  SPOND_USERNAME: ${{ secrets.SPOND_USERNAME }}
  SPOND_PASSWORD: ${{ secrets.SPOND_PASSWORD }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: install dependancies
        run: npm ci

      - name: run tests
        run: npm test

  publish-gpr:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/

      - name: install dependancies
        run: npm ci

      - name: publish to github package registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
